import type { Branch, ContentCollection } from "@/types/content";

// 네이버 플레이스에서 확인한 지점만 공개하고, 나머지 원고 후보는 계속 초안으로 둡니다.
const candidateNames = [
  "메이원헤어 지축점",
  "메이원헤어 야당2점",
  "메이원헤어 성수점",
  "메이원헤어 천안아산점",
  "메이원헤어 송파 헬리오시티역점",
] as const;

const confirmedAt = "2026-09-28T00:00:00+09:00";

export const branches: ContentCollection<Branch> = {
  sourceState: "pending",
  records: [
    {
      id: "asan-tangjeong",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 아산탕정점",
      region: "아산시",
      address: "충남 아산시 탕정면 탕정면로22번길 15-11 1층",
      operationState: "active",
      hours: "월·화·목 10:00–22:00 · 수·금~일 10:00–20:00",
      phone: "0507-1355-5524",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1364245796/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1364245796/home",
      directions: "탕정 지중해마을, 탕정면 복지센터 인근. 트라팰리스 지중해마을 버스정류장 도보 4분, 탕정면사무소 지중해마을 버스정류장 도보 2분. 대표원장 심야 영업은 매장에 전화로 문의하세요.",
      parking: "주차 가능",
      amenities: ["헤어스파", "두피클리닉", "남성전문/바버샵", "심야영업", "탈모관리", "무선 인터넷", "반려동물 동반", "유아의자"],
    },
    {
      id: "migeum",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 미금점",
      region: "분당구",
      address: "경기 성남시 분당구 돌마로 52 MD프라자 2층",
      operationState: "active",
      hours: "화~일 10:00–20:00",
      closedDays: "매주 월요일",
      phone: "0507-1368-0224",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1509347542/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1509347542/home",
      directions: "미금역 6번 출구에서 41m, 써브웨이 건물 2층입니다.",
      parking: "주차 가능",
      amenities: ["헤어스파", "두피클리닉", "유아전용의자", "남성전문/바버샵", "무선 인터넷", "유아의자", "반려동물 동반"],
    },
    {
      id: "western-dom",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 웨스턴돔점",
      region: "일산동구",
      address: "경기 고양시 일산동구 정발산로 27 306호, 307호",
      operationState: "active",
      hours: "월~금 11:00–20:00 · 토~일 10:00–19:00",
      phone: "0507-1459-8857",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1543258765/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1543258765/home",
      directions: "정발산역 1번 출구에서 도보 약 3분(369m), 팀홀튼 건물 3층입니다. 자차 방문 시 네이버 지도에서 매장명 또는 ‘진원프라자’를 검색하면 무료 주차 최대 3시간 30분을 지원합니다.",
      parking: "무료 주차 지원 · 최대 3시간 30분",
      amenities: ["두피클리닉", "헤어스파", "심야영업", "유아의자", "무선 인터넷", "반려동물 동반"],
    },
    {
      id: "yadang",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 야당점",
      region: "파주시",
      address: "경기 파주시 경의로 1092 유은타워3차 2층, 3층",
      operationState: "active",
      hours: "월~금 11:00–20:30 · 토~일 10:30–20:00",
      phone: "0507-1354-5018",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1242621738/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1242621738/home",
      directions: "야당역 2번 출구에서 도보 약 5분(337m), 롯데리아 건물. 월~목은 3층만, 금~일은 2·3층을 운영합니다.",
      parking: "주차 가능",
      amenities: ["헤어스파", "남성전문/바버샵", "유아전용의자", "반려동물 동반", "무선 인터넷", "유아의자"],
    },
    {
      id: "unjeong",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 운정점",
      region: "파주시",
      address: "경기 파주시 경의로 1218 월드타워12차 5층 512호",
      operationState: "active",
      hours: "매일 10:30–20:00",
      phone: "0507-1450-0628",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/2048698939/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/2048698939/home",
      directions: "운정역 1번 출구에서 약 600m, 메가커피 건물 5층입니다. 다른 건물 주차는 할인되지 않습니다.",
      parking: "주차 가능 · 다른 건물 주차 할인 불가",
      amenities: ["두피클리닉", "남성전문/바버샵", "헤어스파", "무선 인터넷", "반려동물 동반"],
    },
    {
      id: "samsong",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 삼송점",
      region: "고양시 덕양구",
      address: "경기 고양시 덕양구 삼송로 210 2층",
      operationState: "active",
      hours: "매일 10:30–20:00",
      phone: "0507-1466-9918",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1583152395/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1583152395/home",
      directions: "삼송역 6번 출구에서 31m, 출구 앞 썬앤빌 건물 2층 안쪽입니다. 위치 안내 전화 02-381-6664.",
      parking: "주차 가능",
      amenities: ["심야영업", "헤어스파", "두피클리닉", "무선 인터넷", "유아의자", "반려동물 동반"],
    },
    {
      id: "haengdang",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원헤어 행당점",
      region: "성동구",
      address: "서울 성동구 행당로 108-1 1층",
      operationState: "active",
      hours: "매일 10:00–20:00",
      phone: "0507-1333-0501",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/2055343643/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/2055343643/home",
      directions: "행당역 3번 출구에서 266m(도보 약 3분). 왕십리역 10번 출구에서는 도보 약 7~8분입니다.",
      parking: "주차 가능",
      amenities: ["남성전문/바버샵", "헤어스파", "두피클리닉", "무선 인터넷", "유아의자", "반려동물 동반"],
    },
    {
      id: "yeongdeungpo-gu-office-mens",
      publicationState: "published",
      reviewState: "confirmed",
      confirmedAt,
      officialName: "메이원맨즈헤어 영등포구청점",
      region: "영등포구",
      address: "서울 영등포구 국회대로36길 10 2층",
      operationState: "active",
      hours: "매일 11:00–20:00",
      phone: "02-2676-3339",
      bookingUrl: "https://pcmap.place.naver.com/hairshop/1155609980/booking?entry=bmp",
      placeUrl: "https://pcmap.place.naver.com/hairshop/1155609980/home",
      directions: "영등포구청역 4번 출구에서 도보 약 2분(141m).",
      parking: "주차 가능",
      amenities: ["남성전문/바버샵", "1인미용실", "헤어스파", "무선 인터넷", "반려동물 동반"],
    },
    ...candidateNames.map((officialName, index) => ({
      id: `branch-candidate-${String(index + 1).padStart(2, "0")}`,
      publicationState: "draft" as const,
      reviewState: "pending" as const,
      officialName,
      operationState: "unknown" as const,
    })),
  ],
};
